sudo: required
language: node_js

services:
  - docker
  - xvfb

branches:
  only:
    - master
    - /^release-[0-9]+\..*$/
addons:
  packages:
    - openjdk-8-jdk
addons:
  chrome: stable
# addons:
#   apt:
#     update: true
#     sources:
#       - google-chrome
#     packages:
#       - dpkg
#       - google-chrome-stable

addons:
  sonarcloud:
    organization: "open-cluster-management"
    token:
      secure: "stfsRk8QKfns8hqznhrVmaEN0jvisW3aGF16wKh9necbxU5YxmA4lyusGbgltqQrZbAA5w23u5g829thLEdQUYcZOWn2UciYAhCzz1YfP34Ac+RIztJ92gc1VauQ6cSuSZbQ/2kmpaLD3OgdG5AJjrJtlcHGNAal2y5JJk+O+gB5RddADiA2TqpvBYcMZTiSBgcfgTYVWgSANbtjTtcj62dLLeaVRT4FADk6jrukD363RKTnJnQ+xBz+STn2vyBs3OENznciXBc5o0tCsebO7DOQAnbHccyxaNEp+qK34tH1xfVY04opy0f0cJ6UUI9PmI6cwt7BNTupYLfPsBknlz8mEDOazR+aaxUGloJDpQZ5oqPYYOjNIj0SI3zTgxLUgZ5PHOmhf+j9Ld/LJM2U3QiulL65C/j7Y/GuOi+VzUTHh8mtnPP30k2Y4rh1SPaInJhtTqOeytU4y2/FSmD9N5JBY8CguoKz6RVjnoBxBySvC6MIob6CfJgYlXuc2tu+l6lHqokPaZemnKXc3ahWJlADTWH3CI1zyXINLj7KAv4GLmi64BMFehwqH41BQUVQL2dwGWwfGLVhJ0mMohPL5J/HG7c4WPpvtzxI5Xg9SeihqCWavz0o9/5z/+Fcc6BV/u0BPDkNDCG8OGAwWK/idbm2V3Iw5iMBRLt8ufkxJ+8="

env:
  global:
    # Required
    - OS=linux
    - COMPONENT_TAG_EXTENSION="-${TRAVIS_COMMIT}"
    # Component Specific
    - COMPONENT_INIT_COMMAND=${TRAVIS_BUILD_DIR}/build/install-dependencies.sh
    - COMPONENT_BUILD_COMMAND=${TRAVIS_BUILD_DIR}/build/build.sh
    - COMPONENT_UNIT_TEST_COMMAND=${TRAVIS_BUILD_DIR}/build/run-unit-tests.sh
    - COMPONENT_E2E_TEST_COMMAND=${TRAVIS_BUILD_DIR}/build/run-e2e-tests.sh

stages:
  - build
  - unit-test
  - test-e2e
  - publish
 
before_script:
  - make init

jobs:
  include:
    - stage: build
      name: "Build the image"
      script:
        - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then export COMPONENT_TAG_EXTENSION="-PR${TRAVIS_PULL_REQUEST}-${TRAVIS_COMMIT}"; fi;
        - make component/build
        - make component/push
        - if [ "$IMAGE_SCAN" != "false" ]; then make security/scans; fi;
    - stage: unit-test
      name: "Build and run unit tests"
      script:
        - make copyright-check TRAVIS_BRANCH=${TRAVIS_BRANCH} TRAVIS_PULL_REQUEST_BRANCH=${TRAVIS_PULL_REQUEST_BRANCH}
        - make sonar/js/jest-init
        - make component/test/unit
        - make sonar/js
    - stage: test-e2e
      name: "Run e2e tests"
      if: type = pull_request
      script:
        # - sudo apt-get -y install google-chrome-stable
        - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then export COMPONENT_TAG_EXTENSION="-PR${TRAVIS_PULL_REQUEST}-${TRAVIS_COMMIT}"; fi;
        - make component/pull
        - make component/test/e2e
        - make e2e-test
        - make e2e-logs
    - stage: publish
      name: "Publish the image to quay with an official version/sha tag and publish entry to integration pipeline stage"
      if: type = push AND branch =~ /^release-[0-9]+\..*$/
      script:
        - make pipeline-manifest/update PIPELINE_MANIFEST_COMPONENT_SHA256=${TRAVIS_COMMIT} PIPELINE_MANIFEST_COMPONENT_REPO=${TRAVIS_REPO_SLUG} PIPELINE_MANIFEST_BRANCH=${TRAVIS_BRANCH}
