sudo: required
language: node_js
node_js:
  - 10

arch:
  - amd64
  - ppc64le
os: linux

services:
  - docker
  - xvfb

branches:
  only:
    - master
    - dev
    - /^[0-9]+\..*$/
    - /^v[0-9]+\..*$/
    - /^release-[0-9]+\..*$/

env:
  global:
    - COMPONENT_TAG_EXTENSION="-${TRAVIS_COMMIT}"

stages:
  - build
  - unit-test
  - test-e2e
  - publish
  
jobs:
  include:
    - stage: build
      before_install:
        - make init
      script:
        - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then export COMPONENT_TAG_EXTENSION="-PR${TRAVIS_PULL_REQUEST}-${TRAVIS_COMMIT}"; fi;
        - |
          make local
          make image
