sudo: required
language: node_js

os: linux

services:
  - docker
  - xvfb

addons:
  packages:
    - openjdk-8-jdk
  chrome: stable

branches:
  only:
    - master
    - dev
    - /^[0-9]+\..*$/
    - /^v[0-9]+\..*$/
    - /^release-[0-9]+\..*$/

env:
  global:
    # Required
    - OS=linux
    - COMPONENT_TAG_EXTENSION="-${TRAVIS_COMMIT}"
    # Component Specific
    - COMPONENT_TYPE="make"
    - COMPONENT_BUILD_COMMAND=${TRAVIS_BUILD_DIR}/build.sh

stages:
  - unit-test
  - build
  # - test-e2e
  - publish
  
before_install:
  - make init 

jobs:
  include:
    - stage: unit-test
      name: "Build and run unit tests"
      script:
        - make unit-test
    - stage: build
      name: "Build the image"
      script:
        - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then export COMPONENT_TAG_EXTENSION="-PR${TRAVIS_PULL_REQUEST}-${TRAVIS_COMMIT}"; fi;
        - make local
        - make component/push
    - stage: test-e2e
      name: "Run e2e tests"
      if: type = pull_request
      script:
        - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then export COMPONENT_TAG_EXTENSION="-PR${TRAVIS_PULL_REQUEST}-${TRAVIS_COMMIT}"; fi;
        - make e2e-test
    - stage: publish
      name: "Publish the image to quay with an official version/sha tag and publish entry to integration pipeline stage"
      if: type = push AND branch IN ( master )
      script:
        - |
          make 
    
