os:
  - linux
  # - linux-ppc64le
  # - linux-s390

sudo: required
language: node_js

services:
  - docker
  - xvfb

branches:
  only:
    - master
    - dev
    - /^[0-9]+\..*$/
    - /^v[0-9]+\..*$/
    - /^release-[0-9]+\..*$/

env:
  global:
    # Required
    - OS=linux
    - COMPONENT_TAG_EXTENSION="-${TRAVIS_COMMIT}"

before_install:
  - make init

install:
  - npm install
#   - chmod +x copyright-check.sh
#   - make copyright-check
#   - make unit-test

before_script:
  - make local
  - make image
  - make run

stages:
  - install-dependencies
  - build
  - unit-test
  - test-e2e
  - publish
  
jobs:
  include:
    - stage: install-dependencies
      name: "Install dependencies"
      script:
        - |
          make init
    - stage: build
      name: "Build the image and run unit tests"
      script:
        - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then export COMPONENT_TAG_EXTENSION="-PR${TRAVIS_PULL_REQUEST}-${TRAVIS_COMMIT}"; fi;
        - |
          make
          make component/build
          make component/push
