sudo: required
language: node_js
node_js:
  - 10

arch:
  - amd64
  - ppc64le
os: linux

services:
  - docker
  - xvfb

addons:
  packages:
    - openjdk-8-jdk
  chrome: stable

branches:
  only:
    - master
    - dev
    - /^[0-9]+\..*$/
    - /^v[0-9]+\..*$/
    - /^release-[0-9]+\..*$/

env:
  global:
    - COMPONENT_TAG_EXTENSION="-${TRAVIS_COMMIT}"

stages:
  - build
  - unit-test
  - test-e2e
  - publish
  
jobs:
  include:
    - stage: build
      name: "Build the image and run unit tests"
      before_install:
        - make init
      script:
        - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then export COMPONENT_TAG_EXTENSION="-PR${TRAVIS_PULL_REQUEST}-${TRAVIS_COMMIT}"; fi;
        - |
          make local
          make image
          make run
    - stage: unit-test
      name: "Deploy the image to a cluster and run e2e tests"
      script:
        - make unit-test
    - stage: test-e2e
      name: "Deploy the image to a cluster and run e2e tests"
      if: type = pull_request
      script:
        #Check out a clusterpool, set up oc, deploy, run e2e tests, and return clusterpool cluster
        - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then export COMPONENT_TAG_EXTENSION="-PR${TRAVIS_PULL_REQUEST}-${TRAVIS_COMMIT}"; fi;
        - make e2e-test
    - stage: publish
      name: "Publish the image to quay with an official version/sha tag and publish entry to integration pipeline stage"
      if: type = push AND branch IN ( master )
      script:
        - |
          make 
    
