options:
  hub:
    hubClusterURL: https://api.grcui-e2e.dev08.red-chesterfield.com:6443
    user: kubeadmin
    password: i2Usu-sESWd-AT7Q4-yKFYJ
    baseURL: https://multicloud-console.apps.grcui-e2e.dev08.red-chesterfield.com