options:
  hub:
    hubClusterURL: https://api.policy-grc-cp-autoclaims-2764w.dev08.red-chesterfield.com:6443
    user: kubeadmin
    password: 5CXEJ-NyTM6-qnTDu-cffBI
    baseURL: https://localhost:3000/multicloud/policies